server:
  port: 8765

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutMilliseconds: 2000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: currency-rate-service
          uri: lb://currency-rate
          predicates:
            - Path=/api/v1/accounts/**, /api/v1/accounts, /api/v1/accounts/
